language: ruby

rvm:
  - 2.2.10
  - 2.3.7
  - 2.4.4
  - 2.5.1
  - 2.6.0-preview2
  - ruby-head
  - jruby-9.2.0.0

before_install:
  - gem update --system
  - gem update --remote bundler

script:
  - bundle exec rake
  - bundle exec rubocop
  - bundle audit check --update
